public enum KeyEventCode: CInt {
    case unknown = 0        //AKEYCODE_UNKNOWN
    case softLeft           //AKEYCODE_SOFT_LEFT
    case softRight          //AKEYCODE_SOFT_RIGHT
    case home               //AKEYCODE_HOME
    case back               //AKEYCODE_BACK
    case call               //AKEYCODE_CALL
    case endcall            //AKEYCODE_ENDCALL
    case _0                 //AKEYCODE_0
    case _1                 //AKEYCODE_1
    case _2                 //AKEYCODE_2
    case _3                 //AKEYCODE_3
    case _4                 //AKEYCODE_4
    case _5                 //AKEYCODE_5
    case _6                 //AKEYCODE_6
    case _7                 //AKEYCODE_7
    case _8                 //AKEYCODE_8
    case _9                 //AKEYCODE_9
    case star               //AKEYCODE_STAR
    case pound              //AKEYCODE_POUND
    case dpadUp             //AKEYCODE_DPAD_UP
    case dpadDown           //AKEYCODE_DPAD_DOWN
    case dpadLeft           //AKEYCODE_DPAD_LEFT
    case dpadRight          //AKEYCODE_DPAD_RIGHT
    case dpadCenter         //AKEYCODE_DPAD_CENTER
    case volumeUp           //AKEYCODE_VOLUME_UP
    case volumeDown         //AKEYCODE_VOLUME_DOWN
    case power              //AKEYCODE_POWER
    case camera             //AKEYCODE_CAMERA
    case clear              //AKEYCODE_CLEAR
    case a                  //AKEYCODE_A
    case b                  //AKEYCODE_B
    case c                  //AKEYCODE_C
    case d                  //AKEYCODE_D
    case e                  //AKEYCODE_E
    case f                  //AKEYCODE_F
    case g                  //AKEYCODE_G
    case h                  //AKEYCODE_H
    case i                  //AKEYCODE_I
    case j                  //AKEYCODE_J
    case k                  //AKEYCODE_K
    case l                  //AKEYCODE_L
    case m                  //AKEYCODE_M
    case n                  //AKEYCODE_N
    case o                  //AKEYCODE_O
    case p                  //AKEYCODE_P
    case q                  //AKEYCODE_Q
    case r                  //AKEYCODE_R
    case s                  //AKEYCODE_S
    case t                  //AKEYCODE_T
    case u                  //AKEYCODE_U
    case v                  //AKEYCODE_V
    case w                  //AKEYCODE_W
    case x                  //AKEYCODE_X
    case y                  //AKEYCODE_Y
    case z                  //AKEYCODE_Z
    case comma              //AKEYCODE_COMMA
    case period             //AKEYCODE_PERIOD
    case altLeft            //AKEYCODE_ALT_LEFT
    case altRight           //AKEYCODE_ALT_RIGHT
    case shiftLeft          //AKEYCODE_SHIFT_LEFT
    case shiftRight         //AKEYCODE_SHIFT_RIGHT
    case tab                //AKEYCODE_TAB
    case space              //AKEYCODE_SPACE
    case sym                //AKEYCODE_SYM
    case explorer           //AKEYCODE_EXPLORER
    case envelope           //AKEYCODE_ENVELOPE
    case enter              //AKEYCODE_ENTER
    case del                //AKEYCODE_DEL
    case grave              //AKEYCODE_GRAVE
    case minus              //AKEYCODE_MINUS
    case equals             //AKEYCODE_EQUALS
    case leftBracket        //AKEYCODE_LEFT_BRACKET
    case rightBracket       //AKEYCODE_RIGHT_BRACKET
    case backslash          //AKEYCODE_BACKSLASH
    case semicolon          //AKEYCODE_SEMICOLON
    case apostrophe         //AKEYCODE_APOSTROPHE
    case slash              //AKEYCODE_SLASH
    case at                 //AKEYCODE_AT
    case num                //AKEYCODE_NUM
    case headsethook        //AKEYCODE_HEADSETHOOK
    case focus              //AKEYCODE_FOCUS
    case plus               //AKEYCODE_PLUS
    case menu               //AKEYCODE_MENU
    case notification       //AKEYCODE_NOTIFICATION
    case search             //AKEYCODE_SEARCH
    case mediaPlayPause     //AKEYCODE_MEDIA_PLAY_PAUSE
    case mediaStop          //AKEYCODE_MEDIA_STOP
    case mediaNext          //AKEYCODE_MEDIA_NEXT
    case mediaPrevious      //AKEYCODE_MEDIA_PREVIOUS
    case mediaRewind        //AKEYCODE_MEDIA_REWIND
    case mediaFastForward   //AKEYCODE_MEDIA_FAST_FORWARD
    case mute               //AKEYCODE_MUTE
    case pageUp             //AKEYCODE_PAGE_UP
    case pageDown           //AKEYCODE_PAGE_DOWN
    case pictsymbols        //AKEYCODE_PICTSYMBOLS
    case switchCharset      //AKEYCODE_SWITCH_CHARSET
    case buttonA            //AKEYCODE_BUTTON_A
    case buttonB            //AKEYCODE_BUTTON_B
    case buttonC            //AKEYCODE_BUTTON_C
    case buttonX            //AKEYCODE_BUTTON_X
    case buttonY            //AKEYCODE_BUTTON_Y
    case buttonZ            //AKEYCODE_BUTTON_Y
    case buttonL1           //AKEYCODE_BUTTON_L1
    case buttonR1           //AKEYCODE_BUTTON_R1
    case buttonL2           //AKEYCODE_BUTTON_L2
    case buttonR2           //AKEYCODE_BUTTON_R2
    case buttonThumbL       //AKEYCODE_BUTTON_THUMBL
    case buttonThumbR       //AKEYCODE_BUTTON_THUMBR
    case buttonStart        //AKEYCODE_BUTTON_START
    case buttonSelect       //AKEYCODE_BUTTON_SELECT
    case buttonMode         //AKEYCODE_BUTTON_MODE
    case escape             //AKEYCODE_ESCAPE
    case forwardDel         //AKEYCODE_FORWARD_DEL
    case ctrlLeft           //AKEYCODE_CTRL_LEFT
    case ctrlRight          //AKEYCODE_CTRL_RIGHT
    case capsLock           //AKEYCODE_CAPS_LOCK
    case scrollLock         //AKEYCODE_SCROLL_LOCK
    case metaLeft           //AKEYCODE_META_LEFT
    case metaRight          //AKEYCODE_META_RIGHT
    case function           //AKEYCODE_FUNCTION
    case sysrq              //AKEYCODE_SYSRQ
    case `break`            //AKEYCODE_BREAK
    case moveHome           //AKEYCODE_MOVE_HOME
    case moveEnd            //AKEYCODE_MOVE_END
    case insert             //AKEYCODE_INSERT
    case forward            //AKEYCODE_FORWARD
    case mediaPlay          //AKEYCODE_MEDIA_PLAY
    case mediaPause         //AKEYCODE_MEDIA_PAUSE
    case mediaClose         //AKEYCODE_MEDIA_CLOSE
    case mediaEject         //AKEYCODE_MEDIA_EJECT
    case mediaRecord        //AKEYCODE_MEDIA_RECORD
    case f1                 //AKEYCODE_F1
    case f2                 //AKEYCODE_F2
    case f3                 //AKEYCODE_F3
    case f4                 //AKEYCODE_F4
    case f5                 //AKEYCODE_F5
    case f6                 //AKEYCODE_F6
    case f7                 //AKEYCODE_F7
    case f8                 //AKEYCODE_F8
    case f9                 //AKEYCODE_F9
    case f10                //AKEYCODE_F10
    case f11                //AKEYCODE_F11
    case f12                //AKEYCODE_F12
    case numLock            //AKEYCODE_NUM_LOCK
    case numpad0            //AKEYCODE_NUMPAD_0
    case numpad1            //AKEYCODE_NUMPAD_1
    case numpad2            //AKEYCODE_NUMPAD_2
    case numpad3            //AKEYCODE_NUMPAD_3
    case numpad4            //AKEYCODE_NUMPAD_4
    case numpad5            //AKEYCODE_NUMPAD_5
    case numpad6            //AKEYCODE_NUMPAD_6
    case numpad7            //AKEYCODE_NUMPAD_7
    case numpad8            //AKEYCODE_NUMPAD_8
    case numpad9            //AKEYCODE_NUMPAD_9
    case numpadDivide       //AKEYCODE_NUMPAD_DIVIDE
    case numpadMultiply     //AKEYCODE_NUMPAD_MULTIPLY
    case numpadSubtract     //AKEYCODE_NUMPAD_SUBTRACT
    case numpadAdd          //AKEYCODE_NUMPAD_ADD
    case numpadDot          //AKEYCODE_NUMPAD_DOT
    case numpadComma        //AKEYCODE_NUMPAD_COMMA
    case numpadEnter        //AKEYCODE_NUMPAD_ENTER
    case numpadEquals       //AKEYCODE_NUMPAD_EQUALS
    case numpadLeftParen    //AKEYCODE_NUMPAD_LEFT_PAREN
    case numpadRightParen   //AKEYCODE_NUMPAD_RIGHT_PAREN
    case volumeMute         //AKEYCODE_VOLUME_MUTE
    case info               //AKEYCODE_INFO
    case channelUp          //AKEYCODE_CHANNEL_UP
    case channelDown        //AKEYCODE_CHANNEL_DOWN
    case zoomIn             //AKEYCODE_ZOOM_IN
    case zoomOut            //AKEYCODE_ZOOM_OUT
    case tv                 //AKEYCODE_TV
    case window             //AKEYCODE_WINDOW
    case guide              //AKEYCODE_GUIDE
    case dvr                //AKEYCODE_DVR
    case bookmark           //AKEYCODE_BOOKMARK
    case captions           //AKEYCODE_CAPTIONS
    case settings           //AKEYCODE_SETTINGS
    case tvPower            //AKEYCODE_TV_POWER
    case tvInput            //AKEYCODE_TV_INPUT
    case stbPower           //AKEYCODE_STB_POWER
    case stbInput           //AKEYCODE_STB_INPUT
    case avrPower           //AKEYCODE_AVR_POWER
    case avrInput           //AKEYCODE_AVR_INPUT
    case progRed            //AKEYCODE_PROG_RED
    case progGreen          //AKEYCODE_PROG_GREEN
    case progYellow         //AKEYCODE_PROG_YELLOW
    case progBlue           //AKEYCODE_PROG_BLUE
    case appSwitch          //AKEYCODE_APP_SWITCH
    case button1            //AKEYCODE_BUTTON_1
    case button2            //AKEYCODE_BUTTON_2
    case button3            //AKEYCODE_BUTTON_3
    case button4            //AKEYCODE_BUTTON_4
    case button5            //AKEYCODE_BUTTON_5
    case button6            //AKEYCODE_BUTTON_6
    case button7            //AKEYCODE_BUTTON_7
    case button8            //AKEYCODE_BUTTON_8
    case button9            //AKEYCODE_BUTTON_9
    case button10           //AKEYCODE_BUTTON_10
    case button11           //AKEYCODE_BUTTON_11
    case button12           //AKEYCODE_BUTTON_12
    case button13           //AKEYCODE_BUTTON_13
    case button14           //AKEYCODE_BUTTON_14
    case button15           //AKEYCODE_BUTTON_15
    case button16           //AKEYCODE_BUTTON_16
    case languageSwitch     //AKEYCODE_LANGUAGE_SWITCH
    case mannerMode         //AKEYCODE_MANNER_MODE
    case _3dMode            //AKEYCODE_3D_MODE
    case contacts           //AKEYCODE_CONTACTS
    case calendar           //AKEYCODE_CALENDAR
    case music              //AKEYCODE_MUSIC
    case calculator         //AKEYCODE_CALCULATOR
    case zenkakuHankaku     //AKEYCODE_ZENKAKU_HANKAKU
    case eisu               //AKEYCODE_EISU
    case muhenkan           //AKEYCODE_MUHENKAN
    case henkan             //AKEYCODE_HENKAN
    case katakanaHiragana   //AKEYCODE_KATAKANA_HIRAGANA
    case yen                //AKEYCODE_YEN
    case ro                 //AKEYCODE_RO
    case kana               //AKEYCODE_KANA
    case assist             //AKEYCODE_ASSIST
    case brightnessDown     //AKEYCODE_BRIGHTNESS_DOWN
    case brightnessUp       //AKEYCODE_BRIGHTNESS_UP
    case mediaAudioTrack    //AKEYCODE_MEDIA_AUDIO_TRACK
    case sleep              //AKEYCODE_SLEEP
    case wakeup             //AKEYCODE_WAKEUP
    case pairing            //AKEYCODE_PAIRING
    case mediaTopMenu       //AKEYCODE_MEDIA_TOP_MENU
    case _11                //AKEYCODE_11
    case _12                //AKEYCODE_12
    case lastChannel        //AKEYCODE_LAST_CHANNEL
    case tvDataService      //AKEYCODE_TV_DATA_SERVICE
    case voiceAssist        //AKEYCODE_VOICE_ASSIST
    case tvRadioService     //AKEYCODE_TV_RADIO_SERVICE
    case tvTeletext         //AKEYCODE_TV_TELETEXT
    case tvNumberEntry      //AKEYCODE_TV_NUMBER_ENTRY
    case tvTerrestrialAnalog  //AKEYCODE_TV_TERRESTRIAL_ANALOG
    case tvTerrestrialDigital //AKEYCODE_TV_TERRESTRIAL_DIGITAL
    case tvSatellite        //AKEYCODE_TV_SATELLITE
    case tvSatelliteBs      //AKEYCODE_TV_SATELLITE_BS
    case tvSatelliteCs      //AKEYCODE_TV_SATELLITE_CS
    case tvSatelliteService //AKEYCODE_TV_SATELLITE_SERVICE
    case tvNetwork          //AKEYCODE_TV_NETWORK
    case tvAntennaCable     //AKEYCODE_TV_ANTENNA_CABLE
    case tvInputHdmi1       //AKEYCODE_TV_INPUT_HDMI_1
    case tvInputHdmi2       //AKEYCODE_TV_INPUT_HDMI_2
    case tvInputHdmi3       //AKEYCODE_TV_INPUT_HDMI_3
    case tvInputHdmi4       //AKEYCODE_TV_INPUT_HDMI_4
    case tvInputComposite1  //AKEYCODE_TV_INPUT_COMPOSITE_1
    case tvInputComposite2  //AKEYCODE_TV_INPUT_COMPOSITE_2
    case tvInputComponent1  //AKEYCODE_TV_INPUT_COMPONENT_1
    case tvInputComponent2  //AKEYCODE_TV_INPUT_COMPONENT_2
    case tvInputVga1        //AKEYCODE_TV_INPUT_VGA_1
    case tvAudioDescription        //AKEYCODE_TV_AUDIO_DESCRIPTION
    case tvAudioDescriptionMixUp   //AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP
    case tvAudioDescriptionMixDown //AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN
    case tvZoomMode         //AKEYCODE_TV_ZOOM_MODE
    case tvContentsMenu     //AKEYCODE_TV_CONTENTS_MENU
    case tvMediaContextMenu //AKEYCODE_TV_MEDIA_CONTEXT_MENU
    case tvTimerProgramming //AKEYCODE_TV_TIMER_PROGRAMMING
    case help               //AKEYCODE_HELP
    case navigatePrevious   //AKEYCODE_NAVIGATE_PREVIOUS
    case navigateNext       //AKEYCODE_NAVIGATE_NEXT
    case navigateIn         //AKEYCODE_NAVIGATE_IN
    case navigateOut        //AKEYCODE_NAVIGATE_OUT
    case stemPrimary        //AKEYCODE_STEM_PRIMARY
    case stem1              //AKEYCODE_STEM_1
    case stem2              //AKEYCODE_STEM_2
    case stem3              //AKEYCODE_STEM_3
    case dpadUpLeft         //AKEYCODE_DPAD_UP_LEFT
    case dpadDownLeft       //AKEYCODE_DPAD_DOWN_LEFT
    case dpadUpRight        //AKEYCODE_DPAD_UP_RIGHT
    case dpadDownRight      //AKEYCODE_DPAD_DOWN_RIGHT
    case mediaSkipForward   //AKEYCODE_MEDIA_SKIP_FORWARD
    case mediaSkipBackward  //AKEYCODE_MEDIA_SKIP_BACKWARD
    case mediaStepForward   //AKEYCODE_MEDIA_STEP_FORWARD
    case mediaStepBackward  //AKEYCODE_MEDIA_STEP_BACKWARD
    case softSleep          //AKEYCODE_SOFT_SLEEP
    case cut                //AKEYCODE_CUT
    case copy               //AKEYCODE_COPY
    case paste              //AKEYCODE_PASTE
    case systemNavigationUp    //AKEYCODE_SYSTEM_NAVIGATION_UP
    case systemNavigationDown  //AKEYCODE_SYSTEM_NAVIGATION_DOWN
    case systemNavigationLeft  //AKEYCODE_SYSTEM_NAVIGATION_LEFT
    case systemNavigationRight //AKEYCODE_SYSTEM_NAVIGATION_RIGHT
    case allApps            //AKEYCODE_ALL_APPS
    case refresh            //AKEYCODE_REFRESH
    case thumbsUp           //AKEYCODE_THUMBS_UP
    case thumbsDown         //AKEYCODE_THUMBS_DOWN
    case profileSwitch      //AKEYCODE_PROFILE_SWITCH
    case videoApp1          //AKEYCODE_VIDEO_APP_1
    case videoApp2          //AKEYCODE_VIDEO_APP_2
    case videoApp3          //AKEYCODE_VIDEO_APP_3
    case videoApp4          //AKEYCODE_VIDEO_APP_4
    case videoApp5          //AKEYCODE_VIDEO_APP_5
    case videoApp6          //AKEYCODE_VIDEO_APP_6
    case videoApp7          //AKEYCODE_VIDEO_APP_7
    case videoApp8          //AKEYCODE_VIDEO_APP_8
    case featuredApp1       //AKEYCODE_FEATURED_APP_1
    case featuredApp2       //AKEYCODE_FEATURED_APP_2
    case featuredApp3       //AKEYCODE_FEATURED_APP_3
    case featuredApp4       //AKEYCODE_FEATURED_APP_4
    case demoApp1           //AKEYCODE_DEMO_APP_1
    case demoApp2           //AKEYCODE_DEMO_APP_2
    case demoApp3           //AKEYCODE_DEMO_APP_3
    case demoApp4           //AKEYCODE_DEMO_APP_4
    case keyboardBacklightDown   //AKEYCODE_KEYBOARD_BACKLIGHT_DOWN
    case keyboardBacklightUp     //AKEYCODE_KEYBOARD_BACKLIGHT_UP
    case keyboardBacklightToggle //AKEYCODE_KEYBOARD_BACKLIGHT_TOGGLE
    case stylusButtonPrimary   //AKEYCODE_STYLUS_BUTTON_PRIMARY
    case stylusButtonSecondary //AKEYCODE_STYLUS_BUTTON_SECONDARY
    case stylusButtonTertiary  //AKEYCODE_STYLUS_BUTTON_TERTIARY
    case stylusButtonTail      //AKEYCODE_STYLUS_BUTTON_TAIL
    case recentApps         //AKEYCODE_RECENT_APPS
    case macro1             //AKEYCODE_MACRO_1
    case macro2             //AKEYCODE_MACRO_2
    case macro3             //AKEYCODE_MACRO_3
    case macro4             //AKEYCODE_MACRO_4
    case emojiPicker        //AKEYCODE_EMOJI_PICKER
    case screenshot         //AKEYCODE_SCREENSHOT
    case dictate            //AKEYCODE_DICTATE
    case new                //AKEYCODE_NEW
    case close              //AKEYCODE_CLOSE
    case doNotDisturb       //AKEYCODE_DO_NOT_DISTURB
    case print              //AKEYCODE_PRINT
    case lock               //AKEYCODE_LOCK
    case fullscreen         //AKEYCODE_FULLSCREEN
    case f13                //AKEYCODE_F13
    case f14                //AKEYCODE_F14
    case f15                //AKEYCODE_F15
    case f16                //AKEYCODE_F16
    case f17                //AKEYCODE_F17
    case f18                //AKEYCODE_F18
    case f19                //AKEYCODE_F19
    case f20                //AKEYCODE_F20
    case f21                //AKEYCODE_F21
    case f22                //AKEYCODE_F22
    case f23                //AKEYCODE_F23
    case f24                //AKEYCODE_F24
}
