public enum MotionEventAxis: CInt {
    case x = 0       //AMOTION_EVENT_AXIS_X
    case y           //AMOTION_EVENT_AXIS_Y
    case pressure    //AMOTION_EVENT_AXIS_PRESSURE
    case size        //AMOTION_EVENT_AXIS_SIZE
    case touchMajor  //AMOTION_EVENT_AXIS_TOUCH_MAJOR
    case touchMinor  //AMOTION_EVENT_AXIS_TOUCH_MINOR
    case toolMajor   //AMOTION_EVENT_AXIS_TOOL_MAJOR
    case toolMinor   //AMOTION_EVENT_AXIS_TOOL_MINOR
    case orientation //AMOTION_EVENT_AXIS_ORIENTATION
    case vScroll     //AMOTION_EVENT_AXIS_VSCROLL
    case hScroll     //AMOTION_EVENT_AXIS_HSCROLL
    case z           //AMOTION_EVENT_AXIS_Z
    case rx          //AMOTION_EVENT_AXIS_RX
    case ry          //AMOTION_EVENT_AXIS_RY
    case rz          //AMOTION_EVENT_AXIS_RZ
    case hatX        //AMOTION_EVENT_AXIS_HAT_X
    case hatY        //AMOTION_EVENT_AXIS_HAT_Y
    case lTrigger    //AMOTION_EVENT_AXIS_LTRIGGER
    case rTrigger    //AMOTION_EVENT_AXIS_RTRIGGER
    case throttle    //AMOTION_EVENT_AXIS_THROTTLE
    case rudder      //AMOTION_EVENT_AXIS_RUDDER
    case wheel       //AMOTION_EVENT_AXIS_WHEEL
    case gas         //AMOTION_EVENT_AXIS_GAS
    case brake       //AMOTION_EVENT_AXIS_BRAKE
    case distance    //AMOTION_EVENT_AXIS_DISTANCE
    case tilt        //AMOTION_EVENT_AXIS_TILT
    case scroll      //AMOTION_EVENT_AXIS_SCROLL
    case relativeX   //AMOTION_EVENT_AXIS_RELATIVE_X
    case relativeY   //AMOTION_EVENT_AXIS_RELATIVE_Y
    case generic1    //AMOTION_EVENT_AXIS_GENERIC_1
    case generic2    //AMOTION_EVENT_AXIS_GENERIC_2
    case generic3    //AMOTION_EVENT_AXIS_GENERIC_3
    case generic4    //AMOTION_EVENT_AXIS_GENERIC_4
    case generic5    //AMOTION_EVENT_AXIS_GENERIC_5
    case generic6    //AMOTION_EVENT_AXIS_GENERIC_6
    case generic7    //AMOTION_EVENT_AXIS_GENERIC_7
    case generic8    //AMOTION_EVENT_AXIS_GENERIC_8
    case generic9    //AMOTION_EVENT_AXIS_GENERIC_9
    case generic10   //AMOTION_EVENT_AXIS_GENERIC_10
    case generic11   //AMOTION_EVENT_AXIS_GENERIC_11
    case generic12   //AMOTION_EVENT_AXIS_GENERIC_12
    case generic13   //AMOTION_EVENT_AXIS_GENERIC_13
    case generic14   //AMOTION_EVENT_AXIS_GENERIC_14
    case generic15   //AMOTION_EVENT_AXIS_GENERIC_15
    case generic16   //AMOTION_EVENT_AXIS_GENERIC_16
    case gestureXOffset          //AMOTION_EVENT_AXIS_GESTURE_X_OFFSET
    case gestureYOffset          //AMOTION_EVENT_AXIS_GESTURE_Y_OFFSET
    case gestureScrollXDistance  //AMOTION_EVENT_AXIS_GESTURE_SCROLL_X_DISTANCE
    case gestureScrollYDistance  //AMOTION_EVENT_AXIS_GESTURE_SCROLL_Y_DISTANCE
    case gesturePinchScaleFactor //AMOTION_EVENT_AXIS_GESTURE_PINCH_SCALE_FACTOR
    case gestureSwipeFingerCount //AMOTION_EVENT_AXIS_GESTURE_SWIPE_FINGER_COUNT
}
